<?php namespace CodeDad\Events;

use Slack;
use Illuminate\Support\Facades\Log;
//TODO there is probaby a better way to organize the data to go in to the event and how to send messages. Varred out for debugging
/**
 * Class SlackEventHandler
 * @package CodeDad\Events
 */
class SlackEventHandler
{
    CONST REVIEW_CHANNEL = "#codetest";

    /**
     * Creates a review
     *  @param $event
     */
    public function onReviewCreation($event)
    {
        $user = '@' . $event['request_user'];
        $ticket = $event['jira_ticket'];
        Slack::to(self::REVIEW_CHANNEL)->send("Code Review Request for jira ticket {$ticket} generated by {$user}");
    }

    /**
     * Claim a review from a user
     * @param $event
     */
    public function onReviewClaim($event)
    {
        $orguser = '@' . $event['request_user'];
        $reviewer = '@' . $event['completion_user'];
        $ticket = $event['jira_ticket'];
        Slack::to($orguser)->send("Your ticket {$ticket} has been claimed by {$reviewer}");
        Slack::to(self::REVIEW_CHANNEL)->send("Ticket {$ticket} claimed by {$reviewer}");
    }

    /**
     * Sends out message to original user and channel
     * @param $event
     */
    public function onReviewComplete($event)
    {   $orginUser = "@{$event['request_user']}";
        $reviewer = "@{$event['completion_user']}";
        $comments = $event["completion_comments"];
        $ticket =   $event['jira_ticket'];
        Slack::to($orginUser)->send("Your ticket {$ticket} passed the code review!  Here are {$reviewer}'s comments: {$comments}'");
        Slack::to(self::REVIEW_CHANNEL)->send("{$ticket} passed the code review by {$reviewer}");
    }

    /**
     * Register the listeners for the subscriber.
     *
     * @param
     * @return array
     */
    public function subscribe($events)
    {
        $events->listen('review.submitted', 'CodeDad\Events\SlackEventHandler@onReviewCreation');
        $events->listen('review.claimed', 'CodeDad\Events\SlackEventHandler@onReviewClaim');
        $events->listen('review.completed','CodeDad\Events\SlackEventHandler@onReviewComplete');

    }

}