<?php namespace CodeDad\Events;

use Slack;
use Illuminate\Support\Facades\Log;
//TODO there is probaby a better way to organize the data to go in to the event and how to send messages. Varred out for debugging
/**
 * Class SlackEventHandler
 * @package CodeDad\Events
 */
class SlackEventHandler
{
    CONST REVIEW_CHANNEL = "#codedadtest";
    CONST Deploy_CHANNEL = '#codedadtest';

    /**
     * Creates a review
     *  @param $event
     */
    public function onReviewCreation($event)
    {
        $user = '@' . $event['request_user'];
        $ticket = $event['jira_ticket'];
        Slack::to(self::REVIEW_CHANNEL)->send("Code Review Request for jira ticket {$ticket} generated by {$user}");
    }

    /**
     * Claim a review from a user
     * @param $event
     */
    public function onReviewClaim($event)
    {
        $orguser = '@' . $event['request_user'];
        $reviewer = '@' . $event['completion_user'];
        $ticket = $event['jira_ticket'];
        Slack::to($orguser)->send("Your ticket {$ticket} has been claimed by {$reviewer}");
        Slack::to(self::REVIEW_CHANNEL)->send("Ticket {$ticket} claimed by {$reviewer}");
    }

    /**
     * Sends out message to original user and channel
     * @param $event
     */
    public function onReviewComplete($event)
    {   $orginUser = "@{$event['request_user']}";
        $reviewer = "@{$event['completion_user']}";
        $comments = $event["completion_comments"];
        $ticket =   $event['jira_ticket'];
        Slack::to($orginUser)->send("Your ticket {$ticket} passed the code review!  Here are {$reviewer}'s comments: {$comments}'");
        Slack::to(self::REVIEW_CHANNEL)->send("{$ticket} passed the code review by {$reviewer}");
    }

    public function onReviewDropped($event)
    {
        $ticket =   $event['jira_ticket'];
        Slack::to(self::REVIEW_CHANNEL)->send("Ticket: {$ticket} was dropped and has been placed back onto the queue");
    }


    public function onDeploymentCreation($event){
        $ticket = $event['jira_ticket'];
        Slack::to(self::Deploy_CHANNEL)->send("Ticket {$ticket} is ready for Staging");
    }

    public function onDeploymentStaged($event){
        $ticket = $event['jira_ticket'];
        $user = $event['user'];
        Slack::to(self::Deploy_CHANNEL)->send("Ticket {$ticket} has been deployed to Staging");
        Slack::to("@{$user}")->send("Please verify {$ticket} in Staging");

    }

    public function onStagingValidation($event){
        $ticket = $event['jira_ticket'];
        Slack::to(self::Deploy_CHANNEL)->send("Ticket {$ticket} has been validated in Staging and is ready for deployment");

    }
    public function onDeployment($event)
    {
        $user = $event['user'];
        $ticket = $event['jira_ticket'];
        Slack::to(self::Deploy_CHANNEL)->send("Ticket {$ticket} has been deployed to Production");
        Slack::to("@{$user}")->send("Please verify {$ticket} in Production");

    }
    public function onProductionValidation($event){
        $ticket = $event['jira_ticket'];
        Slack::to(self::Deploy_CHANNEL)->send("Ticket {$ticket} has been validated in Production!");

    }
    /**
     * Register the listeners for the subscriber.
     *
     * @param
     * @return array
     */
    public function subscribe($events)
    {
        $events->listen('review.submitted', 'CodeDad\Events\SlackEventHandler@onReviewCreation');
        $events->listen('review.claimed', 'CodeDad\Events\SlackEventHandler@onReviewClaim');
        $events->listen('review.completed','CodeDad\Events\SlackEventHandler@onReviewComplete');
        $events->listen('review.dropped','CodeDad\Events\SlackEventHandler@onReviewDropped');
        $events->listen('deployment.submitted','CodeDad\Events\SlackEventHandler@onDeploymentCreation');
        $events->listen('deployment.staged','CodeDad\Events\SlackEventHandler@onDeploymentStaged');
        $events->listen('deployment.isValidatedStaging','CodeDad\Events\SlackEventHandler@onStagingValidation');
        $events->listen('deployment.isDeployed','CodeDad\Events\SlackEventHandler@onDeployment');
        $events->listen('deployment.isValidated','CodeDad\Events\SlackEventHandler@onProductionValidation');


    }

}